---
- name: Get Python version when ansible_python_interpreter is defined
  set_fact:
    python_major_version: '{{ ansible_python_version[0:1] }}'
  when: ansible_python_interpreter is defined

- name: Get Python version when ansible_python_interpreter is undefined
  block:
  - name: Verify Python3 import
    script: py3test.py
    register: py3test
    failed_when: False
    changed_when: False

  - set_fact:
      python_major_version: 3
    when: py3test.rc == 0

  - set_fact:
      python_major_version: 2
    when: py3test.failed or py3test.rc != 0

  - set_fact:
      ansible_python_interpreter: '/usr/bin/python{{ python_major_version }}'

  when: ansible_python_interpreter is undefined

- name: Tasks for Python 2
  block:
    - set_fact:
        keycloak_dep_pyOpenSSL: "pyOpenSSL"
  when: python_major_version == 2


- name: Tasks for Python 3
  block:
    - set_fact:
        keycloak_dep_pyOpenSSL: "python3-pyOpenSSL"
  when: python_major_version == 3
